name: Android CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      # Install cmdline-tools and set ANDROID_SDK_ROOT
      - name: Set up Android SDK (cmdline-tools)
        uses: android-actions/setup-android@v3

      # Cash SDK and ~/.android 
      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.ANDROID_SDK_ROOT }}
            ~/.android
          key: sdk-${{ runner.os }}-${{ hashFiles('**/build.gradle*', '**/gradle.properties', 'gradle/libs.versions.toml') }}

      # Install packages (36 → fallback 35)
      - name: Install SDK packages (retry)
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 20
          command: |
            set -eux
            yes | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --channel=0 "platform-tools"
            yes | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --channel=0 "platforms;android-36"
            # Пытаемся 36.0.0, если нет — ставим 35.0.1 (AGP возьмёт актуальный)
            yes | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --channel=0 "build-tools;36.0.0" || \
            yes | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --channel=0 "build-tools;35.0.1"
            sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --list | head -n 80

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v2

      - name: Gradle info
        run: ./gradlew --version

      - name: Run unit tests
        run: ./gradlew test --stacktrace --no-daemon

      - name: Android Lint (debug)
        run: ./gradlew :app:lintDebug --stacktrace --no-daemon
